/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package amatch_generated;

public class amatch_interfaceJNI {

  static {
    try {
        java.lang.System.loadLibrary("amatch");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native String AMATCH_VER_get();
  public final static native int BUFFERFRAMES_get();
  public final static native int VECSAMPS_MONO_get();
  public final static native int SR_get();
  public final static native double SEC_TO_RECORD_get();
  public final static native double SEC_TO_MATCH_get();
  public final static native double DELAY_PER_SEC_get();
  public final static native double SEC_PER_KEY_get();
  public final static native String amatch_version();
  public final static native int num_samples_to_record();
  public final static native double num_sec_to_record();
  public final static native int get_sample_rate();
  public final static native double delay_per_sec();
  public final static native long read_track_fpkeys(String jarg1);
  public final static native int generate_fp_keys_from_in();
  public final static native int match_sample();
  public final static native void get_recorded_samples(float[] jarg1);
  public final static native void put_recorded_samples(short[] jarg1, int jarg2);
  public final static native int get_recorded_samples_size();
  public final static native void clear_recorded_samples();
  public final static native void write_recorded_as_file(String jarg1);
}
