/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package amatch_generated;

public interface amatch_interfaceConstants {
  public final static String AMATCH_VER = amatch_interfaceJNI.AMATCH_VER_get();
  public final static int BUFFERFRAMES = amatch_interfaceJNI.BUFFERFRAMES_get();
  public final static int VECSAMPS_MONO = amatch_interfaceJNI.VECSAMPS_MONO_get();
  public final static int SR = amatch_interfaceJNI.SR_get();
  public final static int SEC_TO_RECORD = amatch_interfaceJNI.SEC_TO_RECORD_get();
  public final static int SEC_TO_MATCH = amatch_interfaceJNI.SEC_TO_MATCH_get();
  public final static int NRECSAMPLES = amatch_interfaceJNI.NRECSAMPLES_get();
  public final static double SEC_PER_KEY = amatch_interfaceJNI.SEC_PER_KEY_get();
}
