/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package amatch_generated;

public class amatch_interfaceJNI {

  static {
    try {
        java.lang.System.loadLibrary("amatch");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native String AMATCH_VER_get();
  public final static native int BUFFERFRAMES_get();
  public final static native int VECSAMPS_MONO_get();
  public final static native int SR_get();
  public final static native int SEC_TO_RECORD_get();
  public final static native int SEC_TO_MATCH_get();
  public final static native int NRECSAMPLES_get();
  public final static native double SEC_PER_KEY_get();
  public final static native String amatch_version();
  public final static native int nrecsamples();
  public final static native long get_amatch_context();
  public final static native boolean open_audio_device();
  public final static native long read_track_fpkeys(String jarg1);
  public final static native void close_audo_device();
  public final static native void skip_samples(int jarg1);
  public final static native int read_audio_in(float[] jarg1, long jarg2);
  public final static native int generate_fp_keys_from_in();
  public final static native int match_sample();
  public final static native int recording();
  public final static native void start_playing();
  public final static native void stop_playing();
  public final static native void pause_playing();
  public final static native void start_recording();
  public final static native void stop_recording();
  public final static native void pause_recording();
  public final static native int player_state();
  public final static native int recorder_state();
  public final static native void get_recorded_samples(float[] jarg1);
  public final static native int get_recorded_samples_size();
  public final static native void write_recorded_as_file(String jarg1);
}
