/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package amatch_generated;

public class amatch_interface implements amatch_interfaceConstants {
  public static String amatch_version() {
    return amatch_interfaceJNI.amatch_version();
  }

  public static int nrecsamples() {
    return amatch_interfaceJNI.nrecsamples();
  }

  public static SWIGTYPE_p_amatch_context get_amatch_context() {
    long cPtr = amatch_interfaceJNI.get_amatch_context();
    return (cPtr == 0) ? null : new SWIGTYPE_p_amatch_context(cPtr, false);
  }

  public static boolean open_audio_device() {
    return amatch_interfaceJNI.open_audio_device();
  }

  public static long read_track_fpkeys(String fn) {
    return amatch_interfaceJNI.read_track_fpkeys(fn);
  }

  public static void close_audo_device() {
    amatch_interfaceJNI.close_audo_device();
  }

  public static void skip_samples(int nsamples) {
    amatch_interfaceJNI.skip_samples(nsamples);
  }

  public static int read_audio_in(float[] inbuffer, long nsamples) {
    return amatch_interfaceJNI.read_audio_in(inbuffer, nsamples);
  }

  public static int generate_fp_keys_from_in() {
    return amatch_interfaceJNI.generate_fp_keys_from_in();
  }

  public static int match_sample() {
    return amatch_interfaceJNI.match_sample();
  }

  public static int recording() {
    return amatch_interfaceJNI.recording();
  }

  public static void start_playing() {
    amatch_interfaceJNI.start_playing();
  }

  public static void stop_playing() {
    amatch_interfaceJNI.stop_playing();
  }

  public static void pause_playing() {
    amatch_interfaceJNI.pause_playing();
  }

  public static void start_recording() {
    amatch_interfaceJNI.start_recording();
  }

  public static void stop_recording() {
    amatch_interfaceJNI.stop_recording();
  }

  public static void pause_recording() {
    amatch_interfaceJNI.pause_recording();
  }

  public static int player_state() {
    return amatch_interfaceJNI.player_state();
  }

  public static int recorder_state() {
    return amatch_interfaceJNI.recorder_state();
  }

  public static void get_recorded_samples(float[] p) {
    amatch_interfaceJNI.get_recorded_samples(p);
  }

  public static int get_recorded_samples_size() {
    return amatch_interfaceJNI.get_recorded_samples_size();
  }

  public static void write_recorded_as_file(String fname) {
    amatch_interfaceJNI.write_recorded_as_file(fname);
  }

}
